// routeData.js

export const routeMap = [
  // --- Drop only ---
  { pattern: "Airport DMK to Hotel Bangkok", trip_type: "Drop only" },
  { pattern: "Airport DMK to Hotel", trip_type: "Drop only" },
  { pattern: "DMK to Hotel", trip_type: "Drop only" },
  { pattern: "Don Mueang Airport to Hotel", trip_type: "Drop only" },
  { pattern: "Hotel to Airport DMK", trip_type: "Drop only" },
  { pattern: "Hotel to DMK Airport", trip_type: "Drop only" },
  { pattern: "Bangkok Hotel to DMK", trip_type: "Drop only" },
  { pattern: "Airport DMK to Hotel Pattaya", trip_type: "Drop only" },
  { pattern: "DMK to Pattaya Hotel", trip_type: "Drop only" },
  { pattern: "Airport BKK Suvarn to Hotel", trip_type: "Drop only" },
  { pattern: "Airport BKK to Hotel", trip_type: "Drop only" },
  { pattern: "BKK to Hotel", trip_type: "Drop only" },
  { pattern: "Suvarnabhumi Airport to Hotel", trip_type: "Drop only" },
  { pattern: "Hotel to Airport BKK Suvarn", trip_type: "Drop only" },
  { pattern: "Hotel to BKK Airport", trip_type: "Drop only" },
  { pattern: "Hotel to Airport BKK", trip_type: "Drop only" },
  { pattern: "Hotel Pattaya - Drop Airport BKK", trip_type: "Drop only" },
  { pattern: "Pattaya Hotel to BKK Airport", trip_type: "Drop only" },
  { pattern: "Drop only", trip_type: "Drop only" },
  { pattern: "Drop to", trip_type: "Drop only" },
  { pattern: "Bangkok to Pattaya drop", trip_type: "Drop only" },
  { pattern: "Pattaya to Bangkok transfer", trip_type: "Drop only" },
  { pattern: "transfer service", trip_type: "Drop only" },
  { pattern: "car transfer", trip_type: "Drop only" },

  // --- Full Day ---
  { pattern: "Bangkok - Khao Yai - Bangkok", trip_type: "Full day" },
  { pattern: "Khao Yai City tour", trip_type: "Full day" },
  { pattern: "Bangkok - kanchanaburi - bangkok", trip_type: "Full day" },
  { pattern: "Bangkok-Kanchanaburi-Bangkok", trip_type: "Full day" },
  { pattern: "Ayutthaya City tour", trip_type: "Full day" },
  { pattern: "Bangkok-Pattaya-Pattaya", trip_type: "Full day" },
  { pattern: "Bangkok - Pattaya - Ending Pattaya", trip_type: "Full day" },
  { pattern: "Full day", trip_type: "Full day" },
  { pattern: "2 days 1 night - full day", trip_type: "Full day" },

  // --- City Tour ---
  { pattern: "Bangkok city tour", trip_type: "City tour" },
  { pattern: "City tour", trip_type: "City tour" },
  { pattern: "City tour Bangkok", trip_type: "City tour" },
  { pattern: "Sightseeing Bangkok", trip_type: "City tour" },
  { pattern: "Pattaya City Tour", trip_type: "City tour" },
  { pattern: "Phuket City Tour", trip_type: "City tour" },
  { pattern: "Khao Yai City Tour", trip_type: "City tour" },
  { pattern: "Airport DMK + City tour", trip_type: "City tour" }
];

export const knownUniqueRoutes = [
  "Airport DMK to Hotel",
  "Bangkok - Khao Yai - Bangkok",
  "Airport DMK + City Tour + Hotel",
  "Bangkok city tour",
  "Bangkok - kanchanaburi - bangkok",
  "Bangkok - pattaya - end pattaya",
  "Hotel Pattaya - Drop Airport BKK",
  "Bangkok City Tour",
  "Ayutthaya Day Trip",
  "Hotel to Airport DMK",
  "Airport DMK to Hotel Pattaya",
  "Hotel Pattaya to Hotel Bangkok",
  "Hotel to Airport BKK Suvarn",
  "Airport DMK to Hotel bangkok",
  "Airport Suvarn to Hotel",
  "Bangkok Hotel to Pattaya Hotel Drop Only",
  "Hotel Pattaya to Hotel Bangkok Drop only",
  "Hotel Bangkok to Airport DMK",
  "Hotel Pattaya to airport DMK DROP ONLY",
  "Airport DMK to Hotel Bangkok",
  "Bangkok City Tour + Drop Hotel Pattaya",
  "Airport DMK to Hotel / Apartment",
  "Hotel to airport DMK",
  "Bangkok - Pattaya - Ending Pattaya",
  "Hotel Marwin Villa to Airport DMK",
  "Airport DMK to Pattaya Full day",
  "Pattaya - Bangkok City tour",
  "Bangkok to Hotel Pattaya Drop Only",
  "Pattaya to Hotel Bangkok Drop Only",
  "Hotel Pattaya - cubic hotel pratunam",
  "Cubic hotel - DMK",
  "Hotel Pattaya - Suvarnabhumi",
  "Bangkok - Khao Yai - Ending Khao Yai",
  "Khao Yai to Bangkok",
  "Hotel Bangkok to Pattaya",
  "Hotel Pattaya to Bangkok",
  "Airport BKK + Icon siam + Hotel",
  "Hotel to Airport BKK",
  "Khao Yai to Airport DMK Full day",
  "Airport DMK to Hotel Pattaya Drop only",
  "Airport BKK to Hotel pattaya",
  "Hotel Night Pattaya to Bangkok Hotel",
  "Airport DMK + City Tour",
  "Airport BKK to Hotel Bangkok"
];

export const airportCodeMap = {
  "Don Mueang": "DMK",
  "DMK": "Don Mueang",
  "Suvarnabhumi": "BKK",
  "BKK": "Suvarnabhumi"
};